g++ -I./ -c -o decode_riscv_BEQ.o decode_riscv_BEQ.cc
g++ -I./ -c -o decode_riscv_BNE.o decode_riscv_BNE.cc
g++ -I./ -c -o decode_riscv_BLT.o decode_riscv_BLT.cc
g++ -I./ -c -o decode_riscv_BLTU.o decode_riscv_BLTU.cc
g++ -I./ -c -o decode_riscv_BGE.o decode_riscv_BGE.cc
g++ -I./ -c -o decode_riscv_BGEU.o decode_riscv_BGEU.cc
g++ -I./ -c -o decode_riscv_JAL.o decode_riscv_JAL.cc
g++ -I./ -c -o decode_riscv_JALR.o decode_riscv_JALR.cc
g++ -I./ -c -o decode_riscv_LW.o decode_riscv_LW.cc
g++ -I./ -c -o decode_riscv_LH.o decode_riscv_LH.cc
g++ -I./ -c -o decode_riscv_LB.o decode_riscv_LB.cc
g++ -I./ -c -o decode_riscv_LHU.o decode_riscv_LHU.cc
g++ -I./ -c -o decode_riscv_LBU.o decode_riscv_LBU.cc
g++ -I./ -c -o decode_riscv_SW.o decode_riscv_SW.cc
g++ -I./ -c -o decode_riscv_SH.o decode_riscv_SH.cc
g++ -I./ -c -o decode_riscv_SB.o decode_riscv_SB.cc
g++ -I./ -c -o decode_riscv_ADD.o decode_riscv_ADD.cc
g++ -I./ -c -o decode_riscv_AND.o decode_riscv_AND.cc
g++ -I./ -c -o decode_riscv_OR.o decode_riscv_OR.cc
g++ -I./ -c -o decode_riscv_XOR.o decode_riscv_XOR.cc
g++ -I./ -c -o decode_riscv_SLL.o decode_riscv_SLL.cc
g++ -I./ -c -o decode_riscv_SRL.o decode_riscv_SRL.cc
g++ -I./ -c -o decode_riscv_SUB.o decode_riscv_SUB.cc
g++ -I./ -c -o decode_riscv_SRA.o decode_riscv_SRA.cc
g++ -I./ -c -o decode_riscv_SLT.o decode_riscv_SLT.cc
g++ -I./ -c -o decode_riscv_SLTU.o decode_riscv_SLTU.cc
g++ -I./ -c -o decode_riscv_ADDI.o decode_riscv_ADDI.cc
g++ -I./ -c -o decode_riscv_SLTI.o decode_riscv_SLTI.cc
g++ -I./ -c -o decode_riscv_SLTIU.o decode_riscv_SLTIU.cc
g++ -I./ -c -o decode_riscv_ANDI.o decode_riscv_ANDI.cc
g++ -I./ -c -o decode_riscv_ORI.o decode_riscv_ORI.cc
g++ -I./ -c -o decode_riscv_XORI.o decode_riscv_XORI.cc
g++ -I./ -c -o decode_riscv_SLLI.o decode_riscv_SLLI.cc
g++ -I./ -c -o decode_riscv_SRLI.o decode_riscv_SRLI.cc
g++ -I./ -c -o decode_riscv_SRAI.o decode_riscv_SRAI.cc
g++ -I./ -c -o decode_riscv_LUI.o decode_riscv_LUI.cc
g++ -I./ -c -o decode_riscv_AUIPC.o decode_riscv_AUIPC.cc
g++ -I./ -c -o riscv_BEQ.o riscv_BEQ.cc
g++ -I./ -c -o riscv_BNE.o riscv_BNE.cc
g++ -I./ -c -o riscv_BLT.o riscv_BLT.cc
g++ -I./ -c -o riscv_BLTU.o riscv_BLTU.cc
g++ -I./ -c -o riscv_BGE.o riscv_BGE.cc
g++ -I./ -c -o riscv_BGEU.o riscv_BGEU.cc
g++ -I./ -c -o riscv_JAL.o riscv_JAL.cc
g++ -I./ -c -o riscv_JALR.o riscv_JALR.cc
g++ -I./ -c -o riscv_LW.o riscv_LW.cc
g++ -I./ -c -o riscv_LH.o riscv_LH.cc
g++ -I./ -c -o riscv_LB.o riscv_LB.cc
g++ -I./ -c -o riscv_LHU.o riscv_LHU.cc
g++ -I./ -c -o riscv_LBU.o riscv_LBU.cc
g++ -I./ -c -o riscv_SW.o riscv_SW.cc
g++ -I./ -c -o riscv_SH.o riscv_SH.cc
g++ -I./ -c -o riscv_SB.o riscv_SB.cc
g++ -I./ -c -o riscv_ADD.o riscv_ADD.cc
g++ -I./ -c -o riscv_AND.o riscv_AND.cc
g++ -I./ -c -o riscv_OR.o riscv_OR.cc
g++ -I./ -c -o riscv_XOR.o riscv_XOR.cc
g++ -I./ -c -o riscv_SLL.o riscv_SLL.cc
g++ -I./ -c -o riscv_SRL.o riscv_SRL.cc
g++ -I./ -c -o riscv_SUB.o riscv_SUB.cc
g++ -I./ -c -o riscv_SRA.o riscv_SRA.cc
g++ -I./ -c -o riscv_SLT.o riscv_SLT.cc
g++ -I./ -c -o riscv_SLTU.o riscv_SLTU.cc
g++ -I./ -c -o riscv_ADDI.o riscv_ADDI.cc
g++ -I./ -c -o riscv_SLTI.o riscv_SLTI.cc
g++ -I./ -c -o riscv_SLTIU.o riscv_SLTIU.cc
g++ -I./ -c -o riscv_ANDI.o riscv_ANDI.cc
g++ -I./ -c -o riscv_ORI.o riscv_ORI.cc
g++ -I./ -c -o riscv_XORI.o riscv_XORI.cc
g++ -I./ -c -o riscv_SLLI.o riscv_SLLI.cc
g++ -I./ -c -o riscv_SRLI.o riscv_SRLI.cc
g++ -I./ -c -o riscv_SRAI.o riscv_SRAI.cc
g++ -I./ -c -o riscv_LUI.o riscv_LUI.cc
g++ -I./ -c -o riscv_AUIPC.o riscv_AUIPC.cc
g++ -I./ -c -o compute.o compute.cc 
g++ -I./ -c -o help.o ../../uninterpreted_func/uninterpreted_func.cc 
