// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See VmkCPU.h for the primary calling header

#ifndef _VMKCPU_MKNEAR_MEM_H_
#define _VMKCPU_MKNEAR_MEM_H_  // guard

#include "verilated_heavy.h"
#include "VmkCPU__Dpi.h"

//==========

class VmkCPU__Syms;
class VmkCPU_VerilatedVcd;


//----------

VL_MODULE(VmkCPU_mkNear_Mem) {
  public:
    
    // PORTS
    VL_IN8(__PVT__CLK,0,0);
    VL_IN8(__PVT__RST_N,0,0);
    VL_IN8(__PVT__EN_server_reset_request_put,0,0);
    VL_OUT8(__PVT__RDY_server_reset_request_put,0,0);
    VL_IN8(__PVT__EN_server_reset_response_get,0,0);
    VL_OUT8(__PVT__RDY_server_reset_response_get,0,0);
    VL_IN8(__PVT__imem_req_f3,2,0);
    VL_IN8(__PVT__imem_req_priv,1,0);
    VL_IN8(__PVT__imem_req_sstatus_SUM,0,0);
    VL_IN8(__PVT__imem_req_mstatus_MXR,0,0);
    VL_IN8(__PVT__EN_imem_req,0,0);
    VL_OUT8(imem_valid,0,0);
    VL_OUT8(__PVT__imem_is_i32_not_i16,0,0);
    VL_OUT8(__PVT__imem_exc,0,0);
    VL_OUT8(__PVT__imem_exc_code,3,0);
    VL_OUT8(__PVT__imem_master_awvalid,0,0);
    VL_OUT8(__PVT__imem_master_awid,3,0);
    VL_OUT8(__PVT__imem_master_awlen,7,0);
    VL_OUT8(__PVT__imem_master_awsize,2,0);
    VL_OUT8(__PVT__imem_master_awburst,1,0);
    VL_OUT8(__PVT__imem_master_awlock,0,0);
    VL_OUT8(__PVT__imem_master_awcache,3,0);
    VL_OUT8(__PVT__imem_master_awprot,2,0);
    VL_OUT8(__PVT__imem_master_awqos,3,0);
    VL_OUT8(__PVT__imem_master_awregion,3,0);
    VL_IN8(__PVT__imem_master_awready,0,0);
    VL_OUT8(__PVT__imem_master_wvalid,0,0);
    VL_OUT8(__PVT__imem_master_wstrb,7,0);
    VL_OUT8(__PVT__imem_master_wlast,0,0);
    VL_IN8(__PVT__imem_master_wready,0,0);
    VL_IN8(__PVT__imem_master_bvalid,0,0);
    VL_IN8(__PVT__imem_master_bid,3,0);
    VL_IN8(__PVT__imem_master_bresp,1,0);
    VL_OUT8(__PVT__imem_master_bready,0,0);
    VL_OUT8(__PVT__imem_master_arvalid,0,0);
    VL_OUT8(__PVT__imem_master_arid,3,0);
    VL_OUT8(__PVT__imem_master_arlen,7,0);
    VL_OUT8(__PVT__imem_master_arsize,2,0);
    VL_OUT8(__PVT__imem_master_arburst,1,0);
    VL_OUT8(__PVT__imem_master_arlock,0,0);
    VL_OUT8(__PVT__imem_master_arcache,3,0);
    VL_OUT8(__PVT__imem_master_arprot,2,0);
    VL_OUT8(__PVT__imem_master_arqos,3,0);
    VL_OUT8(__PVT__imem_master_arregion,3,0);
    VL_IN8(__PVT__imem_master_arready,0,0);
    VL_IN8(__PVT__imem_master_rvalid,0,0);
    VL_IN8(__PVT__imem_master_rid,3,0);
    VL_IN8(__PVT__imem_master_rresp,1,0);
    VL_IN8(__PVT__imem_master_rlast,0,0);
    VL_OUT8(__PVT__imem_master_rready,0,0);
    VL_IN8(__PVT__dmem_req_op,0,0);
    VL_IN8(__PVT__dmem_req_f3,2,0);
    VL_IN8(__PVT__dmem_req_priv,1,0);
    VL_IN8(__PVT__dmem_req_sstatus_SUM,0,0);
    VL_IN8(__PVT__dmem_req_mstatus_MXR,0,0);
    VL_IN8(__PVT__EN_dmem_req,0,0);
    VL_OUT8(__PVT__dmem_valid,0,0);
    VL_OUT8(__PVT__dmem_exc,0,0);
    VL_OUT8(__PVT__dmem_exc_code,3,0);
    VL_OUT8(__PVT__dmem_master_awvalid,0,0);
    VL_OUT8(__PVT__dmem_master_awid,3,0);
    VL_OUT8(__PVT__dmem_master_awlen,7,0);
    VL_OUT8(__PVT__dmem_master_awsize,2,0);
    VL_OUT8(__PVT__dmem_master_awburst,1,0);
    VL_OUT8(__PVT__dmem_master_awlock,0,0);
    VL_OUT8(__PVT__dmem_master_awcache,3,0);
    VL_OUT8(__PVT__dmem_master_awprot,2,0);
    VL_OUT8(__PVT__dmem_master_awqos,3,0);
    VL_OUT8(__PVT__dmem_master_awregion,3,0);
    VL_IN8(__PVT__dmem_master_awready,0,0);
    VL_OUT8(__PVT__dmem_master_wvalid,0,0);
    VL_OUT8(__PVT__dmem_master_wstrb,7,0);
    VL_OUT8(__PVT__dmem_master_wlast,0,0);
    VL_IN8(__PVT__dmem_master_wready,0,0);
    VL_IN8(__PVT__dmem_master_bvalid,0,0);
    VL_IN8(__PVT__dmem_master_bid,3,0);
    VL_IN8(__PVT__dmem_master_bresp,1,0);
    VL_OUT8(__PVT__dmem_master_bready,0,0);
    VL_OUT8(__PVT__dmem_master_arvalid,0,0);
    VL_OUT8(__PVT__dmem_master_arid,3,0);
    VL_OUT8(__PVT__dmem_master_arlen,7,0);
    VL_OUT8(__PVT__dmem_master_arsize,2,0);
    VL_OUT8(__PVT__dmem_master_arburst,1,0);
    VL_OUT8(__PVT__dmem_master_arlock,0,0);
    VL_OUT8(__PVT__dmem_master_arcache,3,0);
    VL_OUT8(__PVT__dmem_master_arprot,2,0);
    VL_OUT8(__PVT__dmem_master_arqos,3,0);
    VL_OUT8(__PVT__dmem_master_arregion,3,0);
    VL_IN8(__PVT__dmem_master_arready,0,0);
    VL_IN8(__PVT__dmem_master_rvalid,0,0);
    VL_IN8(__PVT__dmem_master_rid,3,0);
    VL_IN8(__PVT__dmem_master_rresp,1,0);
    VL_IN8(__PVT__dmem_master_rlast,0,0);
    VL_OUT8(__PVT__dmem_master_rready,0,0);
    VL_IN8(__PVT__EN_server_fence_i_request_put,0,0);
    VL_OUT8(__PVT__RDY_server_fence_i_request_put,0,0);
    VL_IN8(__PVT__EN_server_fence_i_response_get,0,0);
    VL_OUT8(__PVT__RDY_server_fence_i_response_get,0,0);
    VL_IN8(__PVT__server_fence_request_put,7,0);
    VL_IN8(__PVT__EN_server_fence_request_put,0,0);
    VL_OUT8(__PVT__RDY_server_fence_request_put,0,0);
    VL_IN8(__PVT__EN_server_fence_response_get,0,0);
    VL_OUT8(__PVT__RDY_server_fence_response_get,0,0);
    VL_IN8(__PVT__EN_sfence_vma,0,0);
    VL_OUT8(__PVT__RDY_sfence_vma,0,0);
    VL_IN(__PVT__imem_req_addr,31,0);
    VL_IN(__PVT__imem_req_satp,31,0);
    VL_OUT(imem_pc,31,0);
    VL_OUT(imem_instr,31,0);
    VL_OUT(__PVT__imem_tval,31,0);
    VL_IN(__PVT__dmem_req_addr,31,0);
    VL_IN(__PVT__dmem_req_satp,31,0);
    VL_OUT64(__PVT__imem_master_awaddr,63,0);
    VL_OUT64(__PVT__imem_master_wdata,63,0);
    VL_OUT64(__PVT__imem_master_araddr,63,0);
    VL_IN64(__PVT__imem_master_rdata,63,0);
    VL_IN64(__PVT__dmem_req_store_value,63,0);
    VL_OUT64(__PVT__dmem_word64,63,0);
    VL_OUT64(__PVT__dmem_st_amo_val,63,0);
    VL_OUT64(__PVT__dmem_master_awaddr,63,0);
    VL_OUT64(__PVT__dmem_master_wdata,63,0);
    VL_OUT64(__PVT__dmem_master_araddr,63,0);
    VL_IN64(__PVT__dmem_master_rdata,63,0);
    
    // LOCAL SIGNALS
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*3:0*/ __PVT__cfg_verbosity;
        CData/*1:0*/ __PVT__rg_state;
        CData/*0:0*/ __PVT__dcache__024RDY_server_flush_response_get;
        CData/*0:0*/ __PVT__icache__024RDY_server_flush_response_get;
        CData/*0:0*/ __PVT__MUX_rg_state__024write_1___05FSEL_2;
        CData/*0:0*/ __PVT__MUX_rg_state__024write_1___05FSEL_3;
        CData/*3:0*/ __PVT__dcache__DOT__cfg_verbosity;
        CData/*3:0*/ __PVT__dcache__DOT__ctr_wr_rsps_pending_crg;
        CData/*6:0*/ __PVT__dcache__DOT__rg_cset_in_cache;
        CData/*6:0*/ __PVT__dcache__DOT__rg_cset_in_cache__024D_IN;
        CData/*0:0*/ __PVT__dcache__DOT__rg_error_during_refill;
        CData/*3:0*/ __PVT__dcache__DOT__rg_exc_code;
        CData/*2:0*/ __PVT__dcache__DOT__rg_f3;
        CData/*0:0*/ __PVT__dcache__DOT__rg_lower_word32_full;
        CData/*0:0*/ __PVT__dcache__DOT__rg_op;
        CData/*3:0*/ __PVT__dcache__DOT__rg_state;
        CData/*0:0*/ __PVT__dcache__DOT__rg_word64_set_in_cache__024EN;
        CData/*0:0*/ __PVT__dcache__DOT__f_fabric_write_reqs__024ENQ;
        CData/*0:0*/ __PVT__dcache__DOT__f_reset_reqs__024ENQ;
        CData/*0:0*/ __PVT__dcache__DOT__f_reset_rsps__024DEQ;
        CData/*0:0*/ __PVT__dcache__DOT__f_reset_rsps__024ENQ;
        CData/*0:0*/ __PVT__dcache__DOT__master_xactor_f_rd_addr__024DEQ;
        CData/*0:0*/ __PVT__dcache__DOT__master_xactor_f_rd_addr__024ENQ;
        CData/*0:0*/ __PVT__dcache__DOT__master_xactor_f_rd_data__024CLR;
        CData/*0:0*/ __PVT__dcache__DOT__master_xactor_f_rd_data__024DEQ;
        CData/*0:0*/ __PVT__dcache__DOT__master_xactor_f_rd_data__024ENQ;
        CData/*0:0*/ __PVT__dcache__DOT__master_xactor_f_wr_addr__024DEQ;
        CData/*0:0*/ __PVT__dcache__DOT__master_xactor_f_wr_data__024DEQ;
        CData/*5:0*/ __PVT__dcache__DOT__master_xactor_f_wr_resp__024D_IN;
        CData/*0:0*/ __PVT__dcache__DOT__master_xactor_f_wr_resp__024ENQ;
        CData/*0:0*/ __PVT__dcache__DOT__soc_map__024m_is_mem_addr;
        CData/*0:0*/ __PVT__dcache__DOT__CAN_FIRE_RL_rl_discard_write_rsp;
        CData/*0:0*/ __PVT__dcache__DOT__CAN_FIRE_RL_rl_fabric_send_write_req;
        CData/*0:0*/ __PVT__dcache__DOT__CAN_FIRE_RL_rl_reset;
        CData/*0:0*/ __PVT__dcache__DOT__WILL_FIRE_RL_rl_cache_refill_rsps_loop;
        CData/*0:0*/ __PVT__dcache__DOT__WILL_FIRE_RL_rl_io_read_req;
        CData/*0:0*/ __PVT__dcache__DOT__WILL_FIRE_RL_rl_io_read_rsp;
        CData/*0:0*/ __PVT__dcache__DOT__WILL_FIRE_RL_rl_probe_and_immed_rsp;
        CData/*0:0*/ __PVT__dcache__DOT__WILL_FIRE_RL_rl_rereq;
        CData/*0:0*/ __PVT__dcache__DOT__WILL_FIRE_RL_rl_start_cache_refill;
        CData/*0:0*/ __PVT__dcache__DOT__MUX_rg_error_during_refill__024write_1___05FSEL_1;
        CData/*0:0*/ __PVT__dcache__DOT__MUX_rg_state__024write_1___05FSEL_2;
        CData/*0:0*/ __PVT__dcache__DOT__MUX_rg_state__024write_1___05FSEL_3;
        CData/*0:0*/ __PVT__dcache__DOT__MUX_rg_state__024write_1___05FSEL_7;
        CData/*7:0*/ __PVT__dcache__DOT__mem_req_wr_data_wstrb___05Fh2700;
        CData/*2:0*/ __PVT__dcache__DOT__value___05Fh17372;
        CData/*2:0*/ __PVT__dcache__DOT__x___05Fh2520;
        CData/*3:0*/ __PVT__dcache__DOT__b___05Fh14485;
        CData/*0:0*/ __PVT__dcache__DOT__NOT_req_f3_BITS_1_TO_0_18_EQ_0b0_19_20_AND_NOT_ETC___05F_d539;
        CData/*0:0*/ __PVT__dcache__DOT__NOT_rg_op_1_2_AND_ram_state_and_ctag_cset_b_re_ETC___05F_d305;
        CData/*0:0*/ __PVT__dcache__DOT__dmem_not_imem_AND_NOT_soc_map_m_is_mem_addr_0___05FETC___05F_d106;
        CData/*0:0*/ __PVT__dcache__DOT__ram_state_and_ctag_cset_b_read___05F5_BITS_21_TO_0_ETC___05F_d102;
        CData/*0:0*/ __PVT__dcache__DOT__req_f3_BITS_1_TO_0_18_EQ_0b0_19_OR_req_f3_BITS_ETC___05F_d548;
        CData/*0:0*/ __PVT__dcache__DOT__rg_op_1_AND_ram_state_and_ctag_cset_b_read___05F5___05FETC___05F_d180;
        CData/*0:0*/ __PVT__dcache__DOT__f_fabric_write_reqs__DOT__full_reg;
        CData/*0:0*/ __PVT__dcache__DOT__f_fabric_write_reqs__DOT__empty_reg;
        CData/*0:0*/ __PVT__dcache__DOT__f_fabric_write_reqs__DOT__error_checks__DOT__deqerror;
        CData/*0:0*/ __PVT__dcache__DOT__f_fabric_write_reqs__DOT__error_checks__DOT__enqerror;
        CData/*0:0*/ __PVT__dcache__DOT__f_reset_reqs__DOT__full_reg;
        CData/*0:0*/ __PVT__dcache__DOT__f_reset_reqs__DOT__empty_reg;
        CData/*0:0*/ __PVT__dcache__DOT__f_reset_reqs__DOT__data0_reg;
        CData/*0:0*/ __PVT__dcache__DOT__f_reset_reqs__DOT__data1_reg;
        CData/*0:0*/ __PVT__dcache__DOT__f_reset_reqs__DOT__error_checks__DOT__deqerror;
        CData/*0:0*/ __PVT__dcache__DOT__f_reset_reqs__DOT__error_checks__DOT__enqerror;
    };
    struct {
        CData/*0:0*/ __PVT__dcache__DOT__f_reset_rsps__DOT__full_reg;
        CData/*0:0*/ __PVT__dcache__DOT__f_reset_rsps__DOT__empty_reg;
        CData/*0:0*/ __PVT__dcache__DOT__f_reset_rsps__DOT__data0_reg;
        CData/*0:0*/ __PVT__dcache__DOT__f_reset_rsps__DOT__data1_reg;
        CData/*0:0*/ __PVT__dcache__DOT__f_reset_rsps__DOT__error_checks__DOT__deqerror;
        CData/*0:0*/ __PVT__dcache__DOT__f_reset_rsps__DOT__error_checks__DOT__enqerror;
        CData/*0:0*/ __PVT__dcache__DOT__master_xactor_f_rd_addr__DOT__full_reg;
        CData/*0:0*/ __PVT__dcache__DOT__master_xactor_f_rd_addr__DOT__empty_reg;
        CData/*0:0*/ __PVT__dcache__DOT__master_xactor_f_rd_addr__DOT__error_checks__DOT__deqerror;
        CData/*0:0*/ __PVT__dcache__DOT__master_xactor_f_rd_addr__DOT__error_checks__DOT__enqerror;
        CData/*0:0*/ __PVT__dcache__DOT__master_xactor_f_rd_data__DOT__full_reg;
        CData/*0:0*/ __PVT__dcache__DOT__master_xactor_f_rd_data__DOT__empty_reg;
        CData/*0:0*/ __PVT__dcache__DOT__master_xactor_f_rd_data__DOT__error_checks__DOT__deqerror;
        CData/*0:0*/ __PVT__dcache__DOT__master_xactor_f_rd_data__DOT__error_checks__DOT__enqerror;
        CData/*0:0*/ __PVT__dcache__DOT__master_xactor_f_wr_addr__DOT__full_reg;
        CData/*0:0*/ __PVT__dcache__DOT__master_xactor_f_wr_addr__DOT__empty_reg;
        CData/*0:0*/ __PVT__dcache__DOT__master_xactor_f_wr_addr__DOT__error_checks__DOT__deqerror;
        CData/*0:0*/ __PVT__dcache__DOT__master_xactor_f_wr_addr__DOT__error_checks__DOT__enqerror;
        CData/*0:0*/ __PVT__dcache__DOT__master_xactor_f_wr_data__DOT__full_reg;
        CData/*0:0*/ __PVT__dcache__DOT__master_xactor_f_wr_data__DOT__empty_reg;
        CData/*0:0*/ __PVT__dcache__DOT__master_xactor_f_wr_data__DOT__error_checks__DOT__deqerror;
        CData/*0:0*/ __PVT__dcache__DOT__master_xactor_f_wr_data__DOT__error_checks__DOT__enqerror;
        CData/*0:0*/ __PVT__dcache__DOT__master_xactor_f_wr_resp__DOT__full_reg;
        CData/*0:0*/ __PVT__dcache__DOT__master_xactor_f_wr_resp__DOT__empty_reg;
        CData/*5:0*/ __PVT__dcache__DOT__master_xactor_f_wr_resp__DOT__data0_reg;
        CData/*5:0*/ __PVT__dcache__DOT__master_xactor_f_wr_resp__DOT__data1_reg;
        CData/*0:0*/ __PVT__dcache__DOT__master_xactor_f_wr_resp__DOT__error_checks__DOT__deqerror;
        CData/*0:0*/ __PVT__dcache__DOT__master_xactor_f_wr_resp__DOT__error_checks__DOT__enqerror;
        CData/*0:0*/ __PVT__f_reset_rsps__DOT__empty_reg;
        CData/*0:0*/ __PVT__f_reset_rsps__DOT__full_reg;
        CData/*0:0*/ __PVT__f_reset_rsps__DOT__error_checks__DOT__deqerror;
        CData/*0:0*/ __PVT__f_reset_rsps__DOT__error_checks__DOT__enqerror;
        CData/*3:0*/ __PVT__icache__DOT__cfg_verbosity;
        CData/*3:0*/ __PVT__icache__DOT__ctr_wr_rsps_pending_crg;
        CData/*6:0*/ __PVT__icache__DOT__rg_cset_in_cache;
        CData/*6:0*/ __PVT__icache__DOT__rg_cset_in_cache__024D_IN;
        CData/*0:0*/ __PVT__icache__DOT__rg_error_during_refill;
        CData/*3:0*/ __PVT__icache__DOT__rg_exc_code;
        CData/*2:0*/ __PVT__icache__DOT__rg_f3;
        CData/*0:0*/ __PVT__icache__DOT__rg_lower_word32_full;
        CData/*0:0*/ __PVT__icache__DOT__rg_op;
        CData/*3:0*/ __PVT__icache__DOT__rg_state;
        CData/*0:0*/ __PVT__icache__DOT__rg_word64_set_in_cache__024EN;
        CData/*0:0*/ __PVT__icache__DOT__f_fabric_write_reqs__024ENQ;
        CData/*0:0*/ __PVT__icache__DOT__f_reset_reqs__024DEQ;
        CData/*0:0*/ __PVT__icache__DOT__f_reset_reqs__024ENQ;
        CData/*0:0*/ __PVT__icache__DOT__f_reset_rsps__024DEQ;
        CData/*0:0*/ __PVT__icache__DOT__master_xactor_f_rd_addr__024DEQ;
        CData/*0:0*/ __PVT__icache__DOT__master_xactor_f_rd_addr__024ENQ;
        CData/*0:0*/ __PVT__icache__DOT__master_xactor_f_rd_data__024CLR;
        CData/*0:0*/ __PVT__icache__DOT__master_xactor_f_rd_data__024DEQ;
        CData/*0:0*/ __PVT__icache__DOT__master_xactor_f_rd_data__024ENQ;
        CData/*0:0*/ __PVT__icache__DOT__master_xactor_f_wr_addr__024DEQ;
        CData/*0:0*/ __PVT__icache__DOT__master_xactor_f_wr_data__024DEQ;
        CData/*5:0*/ __PVT__icache__DOT__master_xactor_f_wr_resp__024D_IN;
        CData/*0:0*/ __PVT__icache__DOT__master_xactor_f_wr_resp__024ENQ;
        CData/*0:0*/ __PVT__icache__DOT__CAN_FIRE_RL_rl_discard_write_rsp;
        CData/*0:0*/ __PVT__icache__DOT__CAN_FIRE_RL_rl_fabric_send_write_req;
        CData/*0:0*/ __PVT__icache__DOT__CAN_FIRE_RL_rl_reset;
        CData/*0:0*/ __PVT__icache__DOT__WILL_FIRE_RL_rl_cache_refill_rsps_loop;
        CData/*0:0*/ __PVT__icache__DOT__WILL_FIRE_RL_rl_io_read_req;
        CData/*0:0*/ __PVT__icache__DOT__WILL_FIRE_RL_rl_io_read_rsp;
        CData/*0:0*/ __PVT__icache__DOT__WILL_FIRE_RL_rl_probe_and_immed_rsp;
        CData/*0:0*/ __PVT__icache__DOT__WILL_FIRE_RL_rl_rereq;
    };
    struct {
        CData/*0:0*/ __PVT__icache__DOT__WILL_FIRE_RL_rl_start_cache_refill;
        CData/*0:0*/ __PVT__icache__DOT__MUX_rg_error_during_refill__024write_1___05FSEL_1;
        CData/*0:0*/ __PVT__icache__DOT__MUX_rg_state__024write_1___05FSEL_2;
        CData/*0:0*/ __PVT__icache__DOT__MUX_rg_state__024write_1___05FSEL_3;
        CData/*0:0*/ __PVT__icache__DOT__MUX_rg_state__024write_1___05FSEL_7;
        CData/*7:0*/ __PVT__icache__DOT__mem_req_wr_data_wstrb___05Fh2700;
        CData/*2:0*/ __PVT__icache__DOT__value___05Fh17372;
        CData/*2:0*/ __PVT__icache__DOT__x___05Fh2520;
        CData/*3:0*/ __PVT__icache__DOT__b___05Fh14485;
        CData/*0:0*/ __PVT__icache__DOT__NOT_rg_op_1_2_AND_ram_state_and_ctag_cset_b_re_ETC___05F_d305;
        CData/*0:0*/ __PVT__icache__DOT__dmem_not_imem_AND_NOT_soc_map_m_is_mem_addr_0___05FETC___05F_d106;
        CData/*0:0*/ __PVT__icache__DOT__ram_state_and_ctag_cset_b_read___05F5_BITS_21_TO_0_ETC___05F_d102;
        CData/*0:0*/ __PVT__icache__DOT__rg_op_1_AND_ram_state_and_ctag_cset_b_read___05F5___05FETC___05F_d180;
        CData/*0:0*/ __PVT__icache__DOT__f_fabric_write_reqs__DOT__full_reg;
        CData/*0:0*/ __PVT__icache__DOT__f_fabric_write_reqs__DOT__empty_reg;
        CData/*0:0*/ __PVT__icache__DOT__f_fabric_write_reqs__DOT__error_checks__DOT__deqerror;
        CData/*0:0*/ __PVT__icache__DOT__f_fabric_write_reqs__DOT__error_checks__DOT__enqerror;
        CData/*0:0*/ __PVT__icache__DOT__f_reset_reqs__DOT__full_reg;
        CData/*0:0*/ __PVT__icache__DOT__f_reset_reqs__DOT__empty_reg;
        CData/*0:0*/ __PVT__icache__DOT__f_reset_reqs__DOT__data0_reg;
        CData/*0:0*/ __PVT__icache__DOT__f_reset_reqs__DOT__data1_reg;
        CData/*0:0*/ __PVT__icache__DOT__f_reset_reqs__DOT__error_checks__DOT__deqerror;
        CData/*0:0*/ __PVT__icache__DOT__f_reset_reqs__DOT__error_checks__DOT__enqerror;
        CData/*0:0*/ __PVT__icache__DOT__f_reset_rsps__DOT__full_reg;
        CData/*0:0*/ __PVT__icache__DOT__f_reset_rsps__DOT__empty_reg;
        CData/*0:0*/ __PVT__icache__DOT__f_reset_rsps__DOT__data0_reg;
        CData/*0:0*/ __PVT__icache__DOT__f_reset_rsps__DOT__data1_reg;
        CData/*0:0*/ __PVT__icache__DOT__f_reset_rsps__DOT__error_checks__DOT__deqerror;
        CData/*0:0*/ __PVT__icache__DOT__f_reset_rsps__DOT__error_checks__DOT__enqerror;
        CData/*0:0*/ __PVT__icache__DOT__master_xactor_f_rd_addr__DOT__full_reg;
        CData/*0:0*/ __PVT__icache__DOT__master_xactor_f_rd_addr__DOT__empty_reg;
        CData/*0:0*/ __PVT__icache__DOT__master_xactor_f_rd_addr__DOT__error_checks__DOT__deqerror;
        CData/*0:0*/ __PVT__icache__DOT__master_xactor_f_rd_addr__DOT__error_checks__DOT__enqerror;
        CData/*0:0*/ __PVT__icache__DOT__master_xactor_f_rd_data__DOT__full_reg;
        CData/*0:0*/ __PVT__icache__DOT__master_xactor_f_rd_data__DOT__empty_reg;
        CData/*0:0*/ __PVT__icache__DOT__master_xactor_f_rd_data__DOT__error_checks__DOT__deqerror;
        CData/*0:0*/ __PVT__icache__DOT__master_xactor_f_rd_data__DOT__error_checks__DOT__enqerror;
        CData/*0:0*/ __PVT__icache__DOT__master_xactor_f_wr_addr__DOT__full_reg;
        CData/*0:0*/ __PVT__icache__DOT__master_xactor_f_wr_addr__DOT__empty_reg;
        CData/*0:0*/ __PVT__icache__DOT__master_xactor_f_wr_addr__DOT__error_checks__DOT__deqerror;
        CData/*0:0*/ __PVT__icache__DOT__master_xactor_f_wr_addr__DOT__error_checks__DOT__enqerror;
        CData/*0:0*/ __PVT__icache__DOT__master_xactor_f_wr_data__DOT__full_reg;
        CData/*0:0*/ __PVT__icache__DOT__master_xactor_f_wr_data__DOT__empty_reg;
        CData/*0:0*/ __PVT__icache__DOT__master_xactor_f_wr_data__DOT__error_checks__DOT__deqerror;
        CData/*0:0*/ __PVT__icache__DOT__master_xactor_f_wr_data__DOT__error_checks__DOT__enqerror;
        CData/*0:0*/ __PVT__icache__DOT__master_xactor_f_wr_resp__DOT__full_reg;
        CData/*0:0*/ __PVT__icache__DOT__master_xactor_f_wr_resp__DOT__empty_reg;
        CData/*5:0*/ __PVT__icache__DOT__master_xactor_f_wr_resp__DOT__data0_reg;
        CData/*5:0*/ __PVT__icache__DOT__master_xactor_f_wr_resp__DOT__data1_reg;
        CData/*0:0*/ __PVT__icache__DOT__master_xactor_f_wr_resp__DOT__error_checks__DOT__deqerror;
        CData/*0:0*/ __PVT__icache__DOT__master_xactor_f_wr_resp__DOT__error_checks__DOT__enqerror;
        SData/*8:0*/ __PVT__dcache__DOT__rg_word64_set_in_cache;
        SData/*8:0*/ __PVT__dcache__DOT__rg_word64_set_in_cache__024D_IN;
        SData/*8:0*/ __PVT__icache__DOT__rg_word64_set_in_cache;
        SData/*8:0*/ __PVT__icache__DOT__rg_word64_set_in_cache__024D_IN;
        IData/*31:0*/ __PVT__v___05Fh1643;
        IData/*31:0*/ __PVT__v___05Fh1794;
        IData/*31:0*/ __PVT__v___05Fh1637;
        IData/*31:0*/ __PVT__v___05Fh1788;
        IData/*31:0*/ __PVT__dcache__DOT__rg_addr;
        IData/*31:0*/ __PVT__dcache__DOT__rg_lower_word32;
        IData/*31:0*/ __PVT__dcache__DOT__rg_pa;
        IData/*31:0*/ __PVT__dcache__DOT__rg_pte_pa;
        WData/*98:0*/ __PVT__dcache__DOT__f_fabric_write_reqs__024D_IN[4];
    };
    struct {
        WData/*96:0*/ __PVT__dcache__DOT__master_xactor_f_rd_addr__024D_IN[4];
        WData/*70:0*/ __PVT__dcache__DOT__master_xactor_f_rd_data__024D_IN[3];
        WData/*96:0*/ __PVT__dcache__DOT__master_xactor_f_wr_addr__024D_IN[4];
        WData/*72:0*/ __PVT__dcache__DOT__master_xactor_f_wr_data__024D_IN[3];
        IData/*31:0*/ __PVT__dcache__DOT__v___05Fh2948;
        IData/*31:0*/ __PVT__dcache__DOT__v___05Fh3848;
        IData/*31:0*/ __PVT__dcache__DOT__v___05Fh3949;
        IData/*31:0*/ __PVT__dcache__DOT__v___05Fh4098;
        IData/*31:0*/ __PVT__dcache__DOT__v___05Fh12540;
        IData/*31:0*/ __PVT__dcache__DOT__v___05Fh14531;
        IData/*31:0*/ __PVT__dcache__DOT__v___05Fh15336;
        IData/*31:0*/ __PVT__dcache__DOT__v___05Fh15578;
        IData/*31:0*/ __PVT__dcache__DOT__v___05Fh17191;
        IData/*31:0*/ __PVT__dcache__DOT__v___05Fh17485;
        IData/*31:0*/ __PVT__dcache__DOT__v___05Fh18585;
        IData/*31:0*/ __PVT__dcache__DOT__v___05Fh18692;
        IData/*31:0*/ __PVT__dcache__DOT__v___05Fh18797;
        IData/*31:0*/ __PVT__dcache__DOT__v___05Fh18877;
        IData/*31:0*/ __PVT__dcache__DOT__v___05Fh19505;
        IData/*31:0*/ __PVT__dcache__DOT__v___05Fh19466;
        IData/*31:0*/ __PVT__dcache__DOT__v___05Fh3483;
        IData/*31:0*/ __PVT__dcache__DOT__v___05Fh19852;
        IData/*31:0*/ __PVT__dcache__DOT__v___05Fh2942;
        IData/*31:0*/ __PVT__dcache__DOT__v___05Fh3477;
        IData/*31:0*/ __PVT__dcache__DOT__v___05Fh3842;
        IData/*31:0*/ __PVT__dcache__DOT__v___05Fh3943;
        IData/*31:0*/ __PVT__dcache__DOT__v___05Fh4092;
        IData/*31:0*/ __PVT__dcache__DOT__v___05Fh12534;
        IData/*31:0*/ __PVT__dcache__DOT__v___05Fh14525;
        IData/*31:0*/ __PVT__dcache__DOT__v___05Fh15330;
        IData/*31:0*/ __PVT__dcache__DOT__v___05Fh15572;
        IData/*31:0*/ __PVT__dcache__DOT__v___05Fh17185;
        IData/*31:0*/ __PVT__dcache__DOT__v___05Fh17479;
        IData/*31:0*/ __PVT__dcache__DOT__v___05Fh18579;
        IData/*31:0*/ __PVT__dcache__DOT__v___05Fh18686;
        IData/*31:0*/ __PVT__dcache__DOT__v___05Fh18791;
        IData/*31:0*/ __PVT__dcache__DOT__v___05Fh18871;
        IData/*31:0*/ __PVT__dcache__DOT__v___05Fh19460;
        IData/*31:0*/ __PVT__dcache__DOT__v___05Fh19499;
        IData/*31:0*/ __PVT__dcache__DOT__v___05Fh19846;
        WData/*98:0*/ __PVT__dcache__DOT__f_fabric_write_reqs__DOT__data0_reg[4];
        WData/*98:0*/ __PVT__dcache__DOT__f_fabric_write_reqs__DOT__data1_reg[4];
        WData/*96:0*/ __PVT__dcache__DOT__master_xactor_f_rd_addr__DOT__data0_reg[4];
        WData/*96:0*/ __PVT__dcache__DOT__master_xactor_f_rd_addr__DOT__data1_reg[4];
        WData/*70:0*/ __PVT__dcache__DOT__master_xactor_f_rd_data__DOT__data0_reg[3];
        WData/*70:0*/ __PVT__dcache__DOT__master_xactor_f_rd_data__DOT__data1_reg[3];
        WData/*96:0*/ __PVT__dcache__DOT__master_xactor_f_wr_addr__DOT__data0_reg[4];
        WData/*96:0*/ __PVT__dcache__DOT__master_xactor_f_wr_addr__DOT__data1_reg[4];
        WData/*72:0*/ __PVT__dcache__DOT__master_xactor_f_wr_data__DOT__data0_reg[3];
        WData/*72:0*/ __PVT__dcache__DOT__master_xactor_f_wr_data__DOT__data1_reg[3];
        IData/*22:0*/ __PVT__dcache__DOT__ram_state_and_ctag_cset__DOT__DOA_R;
        IData/*22:0*/ __PVT__dcache__DOT__ram_state_and_ctag_cset__DOT__DOB_R;
        IData/*22:0*/ __PVT__dcache__DOT__ram_state_and_ctag_cset__DOT__DOA_R2;
        IData/*22:0*/ __PVT__dcache__DOT__ram_state_and_ctag_cset__DOT__DOB_R2;
        IData/*22:0*/ __PVT__dcache__DOT__ram_state_and_ctag_cset__DOT__arb1;
        IData/*22:0*/ __PVT__dcache__DOT__ram_state_and_ctag_cset__DOT__arb2;
        IData/*31:0*/ __PVT__icache__DOT__rg_addr;
        IData/*31:0*/ __PVT__icache__DOT__rg_lower_word32;
        IData/*31:0*/ __PVT__icache__DOT__rg_pa;
        IData/*31:0*/ __PVT__icache__DOT__rg_pte_pa;
        WData/*98:0*/ __PVT__icache__DOT__f_fabric_write_reqs__024D_IN[4];
        WData/*96:0*/ __PVT__icache__DOT__master_xactor_f_rd_addr__024D_IN[4];
        WData/*70:0*/ __PVT__icache__DOT__master_xactor_f_rd_data__024D_IN[3];
        WData/*96:0*/ __PVT__icache__DOT__master_xactor_f_wr_addr__024D_IN[4];
    };
    struct {
        WData/*72:0*/ __PVT__icache__DOT__master_xactor_f_wr_data__024D_IN[3];
        IData/*31:0*/ __PVT__icache__DOT__v___05Fh2948;
        IData/*31:0*/ __PVT__icache__DOT__v___05Fh3848;
        IData/*31:0*/ __PVT__icache__DOT__v___05Fh3949;
        IData/*31:0*/ __PVT__icache__DOT__v___05Fh4098;
        IData/*31:0*/ __PVT__icache__DOT__v___05Fh12540;
        IData/*31:0*/ __PVT__icache__DOT__v___05Fh14531;
        IData/*31:0*/ __PVT__icache__DOT__v___05Fh15336;
        IData/*31:0*/ __PVT__icache__DOT__v___05Fh15578;
        IData/*31:0*/ __PVT__icache__DOT__v___05Fh17191;
        IData/*31:0*/ __PVT__icache__DOT__v___05Fh17485;
        IData/*31:0*/ __PVT__icache__DOT__v___05Fh18585;
        IData/*31:0*/ __PVT__icache__DOT__v___05Fh18692;
        IData/*31:0*/ __PVT__icache__DOT__v___05Fh18797;
        IData/*31:0*/ __PVT__icache__DOT__v___05Fh18877;
        IData/*31:0*/ __PVT__icache__DOT__v___05Fh19505;
        IData/*31:0*/ __PVT__icache__DOT__v___05Fh19466;
        IData/*31:0*/ __PVT__icache__DOT__v___05Fh3483;
        IData/*31:0*/ __PVT__icache__DOT__v___05Fh19852;
        IData/*31:0*/ __PVT__icache__DOT__v___05Fh2942;
        IData/*31:0*/ __PVT__icache__DOT__v___05Fh3477;
        IData/*31:0*/ __PVT__icache__DOT__v___05Fh3842;
        IData/*31:0*/ __PVT__icache__DOT__v___05Fh3943;
        IData/*31:0*/ __PVT__icache__DOT__v___05Fh4092;
        IData/*31:0*/ __PVT__icache__DOT__v___05Fh12534;
        IData/*31:0*/ __PVT__icache__DOT__v___05Fh14525;
        IData/*31:0*/ __PVT__icache__DOT__v___05Fh15330;
        IData/*31:0*/ __PVT__icache__DOT__v___05Fh15572;
        IData/*31:0*/ __PVT__icache__DOT__v___05Fh17185;
        IData/*31:0*/ __PVT__icache__DOT__v___05Fh17479;
        IData/*31:0*/ __PVT__icache__DOT__v___05Fh18579;
        IData/*31:0*/ __PVT__icache__DOT__v___05Fh18686;
        IData/*31:0*/ __PVT__icache__DOT__v___05Fh18791;
        IData/*31:0*/ __PVT__icache__DOT__v___05Fh18871;
        IData/*31:0*/ __PVT__icache__DOT__v___05Fh19460;
        IData/*31:0*/ __PVT__icache__DOT__v___05Fh19499;
        IData/*31:0*/ __PVT__icache__DOT__v___05Fh19846;
        WData/*98:0*/ __PVT__icache__DOT__f_fabric_write_reqs__DOT__data0_reg[4];
        WData/*98:0*/ __PVT__icache__DOT__f_fabric_write_reqs__DOT__data1_reg[4];
        WData/*96:0*/ __PVT__icache__DOT__master_xactor_f_rd_addr__DOT__data0_reg[4];
        WData/*96:0*/ __PVT__icache__DOT__master_xactor_f_rd_addr__DOT__data1_reg[4];
        WData/*70:0*/ __PVT__icache__DOT__master_xactor_f_rd_data__DOT__data0_reg[3];
        WData/*70:0*/ __PVT__icache__DOT__master_xactor_f_rd_data__DOT__data1_reg[3];
        WData/*96:0*/ __PVT__icache__DOT__master_xactor_f_wr_addr__DOT__data0_reg[4];
        WData/*96:0*/ __PVT__icache__DOT__master_xactor_f_wr_addr__DOT__data1_reg[4];
        WData/*72:0*/ __PVT__icache__DOT__master_xactor_f_wr_data__DOT__data0_reg[3];
        WData/*72:0*/ __PVT__icache__DOT__master_xactor_f_wr_data__DOT__data1_reg[3];
        IData/*22:0*/ __PVT__icache__DOT__ram_state_and_ctag_cset__DOT__DOA_R;
        IData/*22:0*/ __PVT__icache__DOT__ram_state_and_ctag_cset__DOT__DOB_R;
        IData/*22:0*/ __PVT__icache__DOT__ram_state_and_ctag_cset__DOT__DOA_R2;
        IData/*22:0*/ __PVT__icache__DOT__ram_state_and_ctag_cset__DOT__DOB_R2;
        IData/*22:0*/ __PVT__icache__DOT__ram_state_and_ctag_cset__DOT__arb1;
        IData/*22:0*/ __PVT__icache__DOT__ram_state_and_ctag_cset__DOT__arb2;
        QData/*63:0*/ __PVT__dcache__024word64;
        QData/*63:0*/ __PVT__dcache__DOT__rg_ld_val;
        QData/*63:0*/ __PVT__dcache__DOT__rg_st_amo_val;
        QData/*63:0*/ __PVT__dcache__DOT__IF_rg_addr_6_BITS_2_TO_0_4_EQ_0x0_18_THEN_ram___05FETC___05F_d157;
        QData/*63:0*/ __PVT__dcache__DOT__IF_rg_f3_16_EQ_0b0_17_THEN_IF_rg_addr_6_BITS_2_ETC___05F_d178;
        QData/*63:0*/ __PVT__dcache__DOT__ld_val___05Fh17594;
        QData/*63:0*/ __PVT__dcache__DOT__mem_req_wr_data_wdata___05Fh2699;
        QData/*63:0*/ __PVT__dcache__DOT___theResult___05F_snd_fst___05Fh2707;
        QData/*63:0*/ __PVT__dcache__DOT__word64___05Fh5094;
        QData/*63:0*/ __PVT__dcache__DOT__ram_word64_set__DOT__DOA_R;
        QData/*63:0*/ __PVT__dcache__DOT__ram_word64_set__DOT__DOB_R;
    };
    struct {
        QData/*63:0*/ __PVT__dcache__DOT__ram_word64_set__DOT__DOA_R2;
        QData/*63:0*/ __PVT__dcache__DOT__ram_word64_set__DOT__DOB_R2;
        QData/*63:0*/ __PVT__dcache__DOT__ram_word64_set__DOT__arb1;
        QData/*63:0*/ __PVT__dcache__DOT__ram_word64_set__DOT__arb2;
        QData/*63:0*/ __PVT__icache__DOT__rg_ld_val;
        QData/*63:0*/ __PVT__icache__DOT__rg_st_amo_val;
        QData/*63:0*/ __PVT__icache__DOT__IF_rg_addr_6_BITS_2_TO_0_4_EQ_0x0_18_THEN_ram___05FETC___05F_d157;
        QData/*63:0*/ __PVT__icache__DOT__IF_rg_f3_16_EQ_0b0_17_THEN_IF_rg_addr_6_BITS_2_ETC___05F_d178;
        QData/*63:0*/ __PVT__icache__DOT__ld_val___05Fh17594;
        QData/*63:0*/ __PVT__icache__DOT__mem_req_wr_data_wdata___05Fh2699;
        QData/*63:0*/ __PVT__icache__DOT___theResult___05F_snd_fst___05Fh2707;
        QData/*63:0*/ __PVT__icache__DOT__word64___05Fh5094;
        QData/*63:0*/ __PVT__icache__DOT__ram_word64_set__DOT__DOA_R;
        QData/*63:0*/ __PVT__icache__DOT__ram_word64_set__DOT__DOB_R;
        QData/*63:0*/ __PVT__icache__DOT__ram_word64_set__DOT__DOA_R2;
        QData/*63:0*/ __PVT__icache__DOT__ram_word64_set__DOT__DOB_R2;
        QData/*63:0*/ __PVT__icache__DOT__ram_word64_set__DOT__arb1;
        QData/*63:0*/ __PVT__icache__DOT__ram_word64_set__DOT__arb2;
    };
    
    // LOCAL VARIABLES
    WData/*70:0*/ __Vdly__dcache__DOT__master_xactor_f_rd_data__DOT__data0_reg[3];
    
    // INTERNAL VARIABLES
  private:
    VmkCPU__Syms* __VlSymsp;  // Symbol table
  public:
    
    // CONSTRUCTORS
  private:
    VL_UNCOPYABLE(VmkCPU_mkNear_Mem);  ///< Copying not allowed
  public:
    VmkCPU_mkNear_Mem(const char* name = "TOP");
    ~VmkCPU_mkNear_Mem();
    
    // INTERNAL METHODS
    void __Vconfigure(VmkCPU__Syms* symsp, bool first);
    static void _combo__TOP__mkCPU__near_mem__5(VmkCPU__Syms* __restrict vlSymsp);
    static void _combo__TOP__mkCPU__near_mem__7(VmkCPU__Syms* __restrict vlSymsp);
  private:
    void _ctor_var_reset() VL_ATTR_COLD;
  public:
    static void _sequent__TOP__mkCPU__near_mem__3(VmkCPU__Syms* __restrict vlSymsp);
    static void _sequent__TOP__mkCPU__near_mem__4(VmkCPU__Syms* __restrict vlSymsp);
    static void _sequent__TOP__mkCPU__near_mem__6(VmkCPU__Syms* __restrict vlSymsp);
    static void _settle__TOP__mkCPU__near_mem__1(VmkCPU__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _settle__TOP__mkCPU__near_mem__2(VmkCPU__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void traceInit(VerilatedVcd* vcdp, void* userthis, uint32_t code);
    static void traceFull(VerilatedVcd* vcdp, void* userthis, uint32_t code);
    static void traceChg(VerilatedVcd* vcdp, void* userthis, uint32_t code);
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);

//----------


#endif  // guard
