g++ -I./ -c -o init_Propagate.o init_Propagate.cc
g++ -I./ -c -o decode_GBHigh_Write.o decode_GBHigh_Write.cc
g++ -I./ -c -o decode_GBHigh_Read.o decode_GBHigh_Read.cc
g++ -I./ -c -o decode_Propagate_prop0.o decode_Propagate_prop0.cc
g++ -I./ -c -o decode_Propagate_prop1.o decode_Propagate_prop1.cc
g++ -I./ -c -o GBHigh_Write.o GBHigh_Write.cc
g++ -I./ -c -o GBHigh_Read.o GBHigh_Read.cc
g++ -I./ -c -o Propagate_prop0.o Propagate_prop0.cc
g++ -I./ -c -o Propagate_prop1.o Propagate_prop1.cc
g++ -I./ -c -o compute.o compute.cc 
g++ -I./ -c -o help.o ../../uninterpreted_func/uninterpreted_func.cc 
